apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: kanban.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanban-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kanban-api
                port:
                  number: 8080
          - path: /hubs
            pathType: Prefix
            backend:
              service:
                name: kanban-api
                port:
                  number: 8080