using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace KanbanBoard.Domain.Entities
{
    //Represents the board entity in the database,
    //it has a one to many relationship with the column entity and
    //a many to many relationship with the user entity through the BoardMember entity
    public class Board
    {
        //The board id is a guid generated by the database when the board is created
        [Key]
        public Guid Id { get; set; }

        //The name of the board, it is required and has a maximum length of 100 characters
        [Required]
        [MaxLength(100)]
        public string Name { get; set; } = string.Empty;

        //The user id of the creator of the board, it is required and it is a string because it is the user id from the identity system which is a string
        [Required]
        public string CreatedBy { get; set; } = string.Empty;

        //The date and time when the board was created, it is set to the current date and time when the board is created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        //The columns of the board, it is a list of column entities that have a foreign key to the board id, it is initialized to an empty list to avoid null reference exceptions
        public List<Column> Columns { get; set; } = [];

        //The members of the board, it is a list of board member entities that have a foreign key to the board id, it is initialized to an empty list to avoid null reference exceptions
        public List<BoardMember> Members { get; set; } = [];
    }
}
